dracut: Drop an emergency-shell if mounts fail
This drops an emergency-shell if the mount of either the partitions
(EFI and /var) or the overlay fails.

Signed-off-by: Gaël PORTAY <gael.portay@collabora.com>

diff --git a/dracut/modules.d/steamos-etc-overlay.sh.in b/dracut/modules.d/steamos-etc-overlay.sh.in
--- a/dracut/modules.d/steamos-etc-overlay.sh.in
+++ b/dracut/modules.d/steamos-etc-overlay.sh.in
@@ -72,11 +72,19 @@ mount_etc_overlay() {
     local upperdir="${sysroot}${overlaydir}/upper"
     local workdir="${sysroot}${overlaydir}/work"
 
+    info "Mounting $lowerdir"
     mount -v \
         -t overlay \
         -o lowerdir=$lowerdir,upperdir=$upperdir,workdir=$workdir \
         overlay \
-        $lowerdir
+        $lowerdir 2>&1 | vinfo
+
+    if ! ismounted "$lowerdir"; then
+        warn "Mounting $lowerdir failed! Compile the kernel with CONFIG_OVERLAY_FS!"
+        warn "*** Dropping you to a shell; the system will continue"
+        warn "*** when you leave the shell."
+        emergency_shell
+    fi
 }
 
 prepare_etc_overlay
diff --git a/dracut/modules.d/steamos-udev-rules.sh.in b/dracut/modules.d/steamos-udev-rules.sh.in
--- a/dracut/modules.d/steamos-udev-rules.sh.in
+++ b/dracut/modules.d/steamos-udev-rules.sh.in
@@ -74,8 +74,15 @@ info "Setting up SteamOS udev rules"
 
 EFI=$(getarg 'steamos.efi=')
 if [ -n "$EFI" ]; then
+    info "Mounting $EFI with -o ro"
     [ -d /efi ] || mkdir /efi
-    mount -o ro "$EFI" /efi
+    mount -o ro "$EFI" /efi 2>&1 | vinfo
+    if ! ismounted "/efi"; then
+        warn "Mounting /efi failed!"
+        warn "*** Dropping you to a shell; the system will continue"
+        warn "*** when you leave the shell."
+        emergency_shell
+    fi
 fi
 load_definitions "/efi/$STEAMOS_PARTDEFS_RELDIR"
 if [ -n "$EFI" ]; then
diff --git a/dracut/modules.d/steamos-var.sh.in b/dracut/modules.d/steamos-var.sh.in
--- a/dracut/modules.d/steamos-var.sh.in
+++ b/dracut/modules.d/steamos-var.sh.in
@@ -22,7 +22,15 @@ mount_var() {
 
     # Mount the /var mountpoint
 
-    mount "/dev/${UDEV_SYMLINKS_RELDIR}/self/var" "$NEWROOT/var"
+    info "Mounting /dev/${UDEV_SYMLINKS_RELDIR}/self/var"
+    mount "/dev/${UDEV_SYMLINKS_RELDIR}/self/var" "$NEWROOT/var" 2>&1 | vinfo
+
+    if ! ismounted "$NEWROOT/var"; then
+        warn "Mounting /var failed!"
+        warn "*** Dropping you to a shell; the system will continue"
+        warn "*** when you leave the shell."
+        emergency_shell
+    fi
 }
 
 mount_var
