Handle grub early config generation when /var is mot mounted
It's possible for a system to be mostly functional when /var hasn't
been mounted (either because of a problem or because it's not
configured as a separate partition). Grub's early config should
support /var boot cases if it's there, but work if it's not.

diff --git a/grub/libexec/steamos-grub-mkearlyconfig.in b/grub/libexec/steamos-grub-mkearlyconfig.in
--- a/grub/libexec/steamos-grub-mkearlyconfig.in
+++ b/grub/libexec/steamos-grub-mkearlyconfig.in
@@ -20,6 +20,7 @@ set -u
 # Helpers
 
 fail() { echo >&2 "$@"; exit 1; }
+warn() { echo >&2 "$@"; }
 
 usage() {
     local status=${1-2}
@@ -62,13 +63,12 @@ while [ $# -gt 0 ]; do
     esac
 done
 
-# Get UUIDs for root and var partitions
-
+# Get UUIDs for root and var (optional) partitions
 ROOTUUID=$(findmnt -no uuid /)
-VARUUID=$(findmnt -no uuid /var)
+VARUUID=$(findmnt -no uuid /var || true)
 
 [ "$ROOTUUID" ] || fail "Failed to get root fs uuid"
-[ "$VARUUID"  ] || fail "Failed to get var fs uuid"
+[ "$VARUUID"  ] || warn "Failed to get var fs uuid"
 
 # Generate the grub early config
 
