steamos-finalize-install: Don't fail if we can't create the trigger file
If for whatever reason we can't create the trigger file
`/var/lib/steamos-atomupd/system-updated`, it's better to log a warning
and continue with the update.

Even if this will result in not running `steamos-post-update.service` on
first boot, the operations are not critical and the system will continue
to work as expected.

Part of https://gitlab.steamos.cloud/holo-team/tasks/-/issues/1803
Helps with https://gitlab.steamos.cloud/holo-team/tasks/-/issues/1833

Signed-off-by: Ludovico de Nittis <ludovico.denittis@collabora.com>
(cherry picked from commit edcc65eea6c606108ea13bf0e0429cf3a8d4cff7)

diff --git a/misc/bin/steamos-finalize-install.in b/misc/bin/steamos-finalize-install.in
--- a/misc/bin/steamos-finalize-install.in
+++ b/misc/bin/steamos-finalize-install.in
@@ -217,5 +217,6 @@ fi
 if in_chroot
 then
     # Trigger steamos-post-update.service on the next boot
-    touch /var/lib/steamos-atomupd/system-updated
+    touch /var/lib/steamos-atomupd/system-updated || \
+        echo "Warning: Failed to create the trigger file /var/lib/steamos-atomupd/system-updated. steamos-post-update.service may not run on first boot." >&2
 fi
