steamos-chroot: Allow multiple concurrent chroots into the same partset
Given that we can't mount two times the same overlay, we were not able
to launch two instances of `steamos-chroot` for the same disk and
partset.

To avoid this limitation, we mount the appropriate /etc overlay in
`/run`, and then bind mount it to all `steamos-chroot` instances that
require it.

By using a shared lock, the last chroot that will exit, will also
unmount the /etc overlay.

Signed-off-by: Ludovico de Nittis <ludovico.denittis@collabora.com>

diff --git a/misc/bin/steamos-chroot.in b/misc/bin/steamos-chroot.in
--- a/misc/bin/steamos-chroot.in
+++ b/misc/bin/steamos-chroot.in
@@ -22,6 +22,9 @@ PARTSET=    # --partset
 NO_OVERLAY= # --no-overlay
 ALLOW_SELF= # --allow-self
 
+DEV_DIR=
+DEV_SHARED_LOCK_FD=
+
 SYMLINKS_DIR=@udev_symlinks_absdir@
 
 [ -e @libdir@/steamos/steamos-partitions-lib ] && \
@@ -30,6 +33,7 @@ SYMLINKS_DIR=@udev_symlinks_absdir@
 
 # Helpers
 
+log () { echo >&2 "$@"; }
 fail() { echo >&2 "$@"; exit 1; }
 
 usage() {
@@ -47,8 +51,7 @@ usage() {
     echo
     echo "By default, also the overlayed /etc will be mounted. Please note that the"
     echo "overlay can only be mounted once, so you can't re-mount the /etc overlay"
-    echo "for 'self', or run multiple chroots for the same disk."
-    echo "Instead, to skip mounting the overlay, you can use the option '--no-overlay'."
+    echo "for 'self'. To workaround this, you can use the option '--no-overlay'."
     echo
     echo "If you want to chroot into the already booted partset, you should explicitly"
     echo "set the option '--allow-self'."
@@ -161,6 +164,40 @@ prepare_chroot_at() {
     local dir=$1
 
     mount -o ro "$ROOTFS_DEVICE" $dir
+
+    if [ -z "$NO_OVERLAY" ]; then
+        local dev_name=${DISK:-this}-${PARTSET}
+        local dev_lock="/run/lock/${dev_name}.flock"
+        local run_steamos_chroot="/run/steamos-chroot"
+        DEV_DIR="${run_steamos_chroot}/${dev_name}"
+
+        mkdir -p "$run_steamos_chroot"
+
+        # Get the shared lock to signal that other chroot instances should not unmount the /etc overlay
+        exec {DEV_SHARED_LOCK_FD}>$dev_lock
+        flock --shared $DEV_SHARED_LOCK_FD
+
+        if [ ! -d "$DEV_DIR" ]; then
+            local dev_exclusive_lock="/run/lock/${dev_name}-exclusive.flock"
+            local lockfd=-1
+
+            exec {lockfd}>$dev_exclusive_lock
+            flock --exclusive --timeout 3 $lockfd || fail "Failed to get the exclusive lock to mount the /etc overlay"
+
+            # Now that we have the lock, check again if the directory is still missing.
+            if [ ! -d "$DEV_DIR" ]; then
+                mkdir -p "$DEV_DIR"
+                mount -o ro "$ROOTFS_DEVICE" "$DEV_DIR"
+                mount "$VAR_DEVICE" "$DEV_DIR/var"
+                mount -t overlay -o "lowerdir=${DEV_DIR}/etc,upperdir=${DEV_DIR}/var/lib/overlays/etc/upper,workdir=${DEV_DIR}/var/lib/overlays/etc/work" none "${DEV_DIR}/etc" || \
+                    fail "Failed to mount the /etc overlay. If it's not required, you could set the '--no-overlay' option"
+            fi
+            flock --unlock --close $lockfd
+        fi
+
+        mount --bind "$DEV_DIR/etc" "$dir/etc"
+    fi
+
     mount --bind /dev  $dir/dev
     mount --bind /proc $dir/proc
     mount --bind /run  $dir/run
@@ -170,10 +207,6 @@ prepare_chroot_at() {
     mount "$EFI_DEVICE" $dir/efi
     mount "$ESP_DEVICE" $dir/esp
     mount "$VAR_DEVICE" $dir/var
-    if [ -z "$NO_OVERLAY" ]; then
-        mount -t overlay -o "lowerdir=$dir/etc,upperdir=$dir/var/lib/overlays/etc/upper,workdir=$dir/var/lib/overlays/etc/work" none "$dir/etc" || \
-        fail "Failed to mount the /etc overlay. You should either set the '--no-overlay' option or, if possible, manually unmount the /etc overlay"
-    fi
     if [ -d $dir/var/boot ]; then
         mount --bind $dir/var/boot $dir/boot
     fi
@@ -188,6 +221,20 @@ cleanup_chroot_at() {
     fi
     if [ -z "$NO_OVERLAY" ]; then
         umount $dir/etc  || :
+
+        if [ -n "$DEV_SHARED_LOCK_FD" ]; then
+            # Try to convert the shared lock into an exlusive one
+            flock --exclusive --timeout 1 "$DEV_SHARED_LOCK_FD" && {
+                # We are the only one that were using this /etc overlay. Clean it up.
+                umount "$DEV_DIR/etc" || :
+                umount "$DEV_DIR/var" || :
+                umount "$DEV_DIR" || :
+                rmdir "$DEV_DIR" || :
+            } || {
+                log "There are other active steamos-chroot instances, do not unmount the /etc overlay"
+            }
+            flock --unlock --close "$DEV_SHARED_LOCK_FD" || :
+        fi
     fi
     umount $dir/var  || :
     umount $dir/esp  || :
