atomic-update: split /var sync into required and optional parts
Try to sync /var in two passes:

  - A mandatory 1st pass which syncs files we _must_ have
  - An optional (ie allowed to fail) 2nd pass for the rest
  - Both passes exclude the directories we _never_ sync

diff --git a/misc/bin/steamos-sync-preserved.in b/misc/bin/steamos-sync-preserved.in
--- a/misc/bin/steamos-sync-preserved.in
+++ b/misc/bin/steamos-sync-preserved.in
@@ -255,11 +255,11 @@ sync_var_mountpoints() {
     local upper_dir="${etc_overlay_in_var}/upper"
     local config
 
-    # We exclude the directories /var/lib/{dkms,modules,pacman}, as they don't
-    # really represent a state that we want to keep, but rather a part of the
-    # rootfs that ends up leaving in /var for technical reasons. These pieces
-    # must be empty on first boot, so that they can be initialized from the
-    # factory that is shipped with the rootfs.
+    # We exclude the directories:
+    #    /var/lib/{dkms,modules,pacman,NetworkManager}
+    # as they don't really represent a state that we want to keep, but rather a
+    # part of the rootfs that ends up leaving in /var for technical reasons.
+    # These pieces must be empty on first boot, so that they can be initialized
     #
     # We also need to exclude /var/boot, which might contain the initrd that
     # was rebuilt to include nvidia drivers built by DKMS. Once again, this is
@@ -269,23 +269,54 @@ sync_var_mountpoints() {
     #
     # --one-file-system makes sure that we ignore all the directories from /home
     # that are bind-mounted onto /var directories.
+    #
+    # --inplace skips the usual copy-to-a-tmpfile-and-move transfer mechanism.
+    # Since we are copying to an empty filesystem we don't need to preserve
+    # anything already on the target, so having the creation of the target be
+    # an atomic operation is unimportant.
+    #
+    # we also do the copy in two phases: 1st the important dirs which we know
+    # are required for proper operation of the OS, then the "nice to have"
+    # directories without which we can still go on working:
 
+    local -a syncargs=(--archive --delete --inplace --one-file-system)
+    ########################################################################
+    # /var/lib directories that MUST NOT be synced:
+    local -e excl=(boot lost+found)
+    local -a libexcl=(dkms modules pacman NetworkManager)
+    local -a exclude=(--exclude="${etc_overlay_in_var}")
+    for x in "${libexcl[@]}"; do exclude+=(--exclude="/lib/$x/"); done
+    for x in "${excl[@]}";    do exclude+=(--exclude="/$x/");     done
+    #########################################################################
+    # /var directories that _may_ be skipped when syncing
+    # in particular we allow log to fail because it may be very large on a
+    # misbehaving or misconfigured system:
+    local -a optd=(cache crash local games mail opt db empty log mnt)
+    local -a optdirs=()
+    for x in "${optd[@]}"; do optdirs+=(--exclude="/$x/"); done
+    #########################################################################
+    # First pass: skip compulsory exclusions _and_ optional targets
     if ! rsync \
-        --archive \
-        --delete \
-        --one-file-system \
-        --exclude="/boot/" \
-        --exclude="/lib/dkms/" \
-        --exclude="/lib/modules/" \
-        --exclude="/lib/pacman/" \
-        --exclude="/lib/NetworkManager/" \
-        --exclude="/lost+found/" \
-        --exclude="${etc_overlay_in_var}" \
-        "$src/" "$dst/"; then
-
-        warn "rsync failed to sync \"$src\" to \"$dst\""
+         "${syncargs[@]}" \
+         "${exclude[@]}" \
+         "${optdirs[@]}" \
+         "$src/" "$dst/"
+    then
+        warn "rsync failed to sync files from \"$src/\" to \"$dst\""
         return 1
     fi
+
+    # Second pass: skip just the compulsory exclusions
+    # This is permitted to fail since everything we _have_ to have should
+    # have been synced in the first pass.
+    if ! rsync \
+         "${syncargs[@]}" \
+         "${exclude[@]}"  \
+         "$src/" "$dst/"
+    then
+        warn "rsync failed to sync optional files from \"$src\" to \"$dst\""
+    fi
+    ########################################################################
 
     config=$(mktemp --tmpdir "etc_config.XXXXXX")
     if [ -z "${config}" ]; then
