steamos-partsets: Take the dev partset into account

diff --git a/misc/bin/steamos-partsets.in b/misc/bin/steamos-partsets.in
--- a/misc/bin/steamos-partsets.in
+++ b/misc/bin/steamos-partsets.in
@@ -96,9 +96,8 @@ OTHER=
 case "$SELF" in
     (A) OTHER=B;;
     (B) OTHER=A;;
-    (Dev) OTHER=A;;
 esac
-[ "$OTHER" ] || fail "Failed to determine 'other' for self=$SELF"
+[ "$OTHER" ] || [ "$SELF" == "Dev"] || fail "Failed to determine 'other' for self=$SELF"
 
 # Get the disk on which SteamOS lives
 
@@ -169,9 +168,15 @@ while read device partuuid typeuuid partlabel; do
             ;;
         ("$SELF")
             group=self
+            if [ "$SELF" == "Dev" ]; then
+                echo "$linkname $partuuid"  >> "$OUTDIR/dev"
+            fi
             ;;
         ("$OTHER")
             group=other
+            ;;
+        ("Dev")
+            group=dev
             ;;
         (*)
             log "Discarding partition '$partlabel' with unexpected suffix '$partset'"
