steamos-update-os-notifier.action: Handle too few arguments
This handles and print a specific error message if no argument is given.

diff --git a/atomic-update/libexec/steamos-update-os-notifier.action.in b/atomic-update/libexec/steamos-update-os-notifier.action.in
--- a/atomic-update/libexec/steamos-update-os-notifier.action.in
+++ b/atomic-update/libexec/steamos-update-os-notifier.action.in
@@ -43,6 +43,10 @@ offline-updates)
     touch /run/steamos/update-other
     ;;
 *)
-    echo "$1: Invalid argument" >&2
+    if [[ ! "$1" ]]; then
+        echo "Too few argument" >&2
+    else
+        echo "$1: Invalid argument" >&2
+    fi
     exit 127
 esac
