holo-post-update-shutdown: Run the migrate finalize install step
After applying an OS update the current steps are:
- Running `post-install.sh`, which:
  - Runs `holo-sync-var` to sync /var and /etc changes
- Runs `*-finalize-install` to install the bootloaders and apply the
necessary config migration
- Running `holo-post-update-shutdown`
  - Runs `holo-sync-var catchup`

The problem with running `holo-sync-var` a second time is that the
config migrations could be lost and overwritten by rsync. E.g. in
finalize install remove the eventual
"/var/lib/overlays/etc/upper/steamos-atomupd/client.conf", but if we
re-run rsync we could bring that file back.

To avoid such issues, with this commit we call finalize install also
from `holo-post-update-shutdown`, this time without re-installing the
bootloaders.

Note that there is no need to also fallback to the
`steamos-boot-install` included in SteamOS images from 2022, because
here we only care about the config migration and we don't need to
install again the bootloaders.

Signed-off-by: Ludovico de Nittis <ludovico.denittis@collabora.com>

diff --git a/misc/libexec/holo-post-update-shutdown.in b/misc/libexec/holo-post-update-shutdown.in
--- a/misc/libexec/holo-post-update-shutdown.in
+++ b/misc/libexec/holo-post-update-shutdown.in
@@ -50,3 +50,12 @@ mount "$VAR_DEVICE_OTHER" /mnt/var
 umount /mnt/var
 umount /mnt
 
+# After executing `holo-sync-var catchup`, we need to run again the migrate finalize install step.
+# We run this even if a part of `holo-sync-var catchup` unexpectedly failed.
+# This ensures that we have the expected files in the new /etc and /var, and that they didn't
+# get overwritten by `holo-sync-var`.
+if ! holo-chroot --partset $UPDATED_SLOT -- holo-finalize-install --no-boot-install \
+  && ! holo-chroot --partset $UPDATED_SLOT -- steamos-finalize-install --no-boot-install
+then
+    warn "Failed to migrate the configuration changes!"
+fi
