atomupd: Add the option --debug
This commit introduces the option debug to print the journal of rauc to
stderr.

Signed-off-by: Gaël PORTAY <gael.portay@collabora.com>

diff --git a/atomic-update/bin/steamos-update-os-plymouth b/atomic-update/bin/steamos-update-os-plymouth
--- a/atomic-update/bin/steamos-update-os-plymouth
+++ b/atomic-update/bin/steamos-update-os-plymouth
@@ -25,12 +25,34 @@ progress() {
     echo "$1%"
 }
 
+while [[ "$#" -ne 0 ]]
+do
+    if [[ "$1" =~ ^(-h|--help)$ ]]
+    then
+        echo "Usage: ${0##*/} [-h|--help] [--debug]"
+        exit 0
+    elif [[ "$1" == "--debug" ]]
+    then
+        debug=true
+    else
+        echo "$1: Invalid argument" >&2
+        exit 1
+    fi
+    shift
+done
+
 while read -r -a words
 do
     # Empty line: skip it!
     if [[ "${#words[@]}" -eq 0 ]]
     then
         continue
+    fi
+
+    # Print the journal to stderr
+    if [[ "${debug:-}" ]]
+    then
+        echo "${words[@]}" >&2
     fi
 
     # Slot needs to be updated with /run/rauc/bundle/*.img.caibx
