atomic-update: Abort an update if we can't sync /var
By using `sync_var_mountpoints [...] || err "Failed to sync [...]"` the
intention was to error out if rsync failed to sync the current `/var`
partition with the target.

However, `set -e` doesn't abort the execution if `sync_var_mountpoints`
is executed with the OR operator. This means that even if `rsync`
failed, we unexpectedly never reached the
`err "Failed to sync var partitions"`.

Instead, we wrap `rsync` inside an `if` to return an error code if
`rsync` fails.

Signed-off-by: Ludovico de Nittis <ludovico.denittis@collabora.com>

diff --git a/atomic-update/rauc/post-install.sh.in b/atomic-update/rauc/post-install.sh.in
--- a/atomic-update/rauc/post-install.sh.in
+++ b/atomic-update/rauc/post-install.sh.in
@@ -241,7 +241,7 @@ sync_var_mountpoints() {
     # enable - which will regenerate it for them, or if they manually flip off
     # the RO mode, they can issue pacman-key manually.
 
-    rsync \
+    if ! rsync \
         --archive \
         --delete \
         --one-file-system \
@@ -254,7 +254,11 @@ sync_var_mountpoints() {
         --exclude="/lib/overlays/etc/upper/os-release" \
         --exclude="/lib/overlays/etc/upper/rauc" \
         --exclude="/lib/overlays/etc/upper/pacman.d/gnupg" \
-        "$src/" "$dst/"
+        "$src/" "$dst/"; then
+
+        warn "rsync failed to sync \"$src\" to \"$dst\""
+        return 1
+    fi
 
     # Explicitly remove and mask/whiteout the .updated files in /var and /etc
     # respectively. Counter intuitively The timestamp stored is for the /usr
