rauc: Preserve a copy of the last /etc changes in /etc/previous
/etc user changes are already stored as tar archives in
`/var/lib/steamos-atomupd/etc_backup/`. However, that brings a couple of
inconveniences:
- End users might not know the existence of these backups
- Searching for a file inside tar archives is not immediately straight
forward

In order to address those pain points, when applying an update we also
keep a plain copy of `/etc` inside `/etc/previous`.
This allows end users to simply run `fd my_missing_file` and get a hit
from `/etc/previous/...`

Signed-off-by: Ludovico de Nittis <ludovico.denittis@collabora.com>

diff --git a/atomic-update/rauc/post-install.sh.in b/atomic-update/rauc/post-install.sh.in
--- a/atomic-update/rauc/post-install.sh.in
+++ b/atomic-update/rauc/post-install.sh.in
@@ -315,6 +315,44 @@ backup_etc_changes() {
     remove_old_files "${backup_dir}" -5 || :
 }
 
+keep_previous_etc_copy() {
+    local src=$1
+    local dst=$2
+    local src_upper_dir_size
+    local free_space
+    local upper_dir="${ETC_OVERLAY_ABSDIR#"/var"}/upper"
+    local previous_etc_dir="${upper_dir}/previous"
+
+    # Remove the eventual "/etc/previous" files copied from $src
+    rm -rf "${dst}${previous_etc_dir}" || :
+    mkdir -p "${dst}${previous_etc_dir}"
+
+    src_upper_dir_size=$(du -s --block-size=1K --exclude "${src}${previous_etc_dir}" "${src}${upper_dir}" | cut -f1)
+
+    free_space=$(df --output=avail --block-size=1K "${dst}${previous_etc_dir}" | tail -n 1)
+
+    if (( free_space < src_upper_dir_size )); then
+        warn "There is not enough free space to keep a copy of the previous /etc edits"
+        return 1
+    fi
+
+    # Include a brief explanation of what `/etc/previous` is supposed to hold
+    printf "%s\n" "The '/etc/previous' directory contains the edited files that you had" \
+        "in '/etc' before you applied the last system update." \
+        "You can find a more detailed explanation of how /etc changes are preserved by" \
+        "reading the header of '${OWD}/${ATOMIC_UPDATE_KEEP_CONF}'" > "${dst}${previous_etc_dir}"/README
+
+    if ! rsync \
+        --archive \
+        --one-file-system \
+        --exclude="/previous" \
+        "${src}${upper_dir}/" "${dst}${previous_etc_dir}/"; then
+
+        warn "rsync failed to sync the /etc changes to the \"previous\" directory"
+        return 1
+    fi
+}
+
 sync_var_mountpoints() {
     local src=$1
     local dst=$2
@@ -466,6 +504,9 @@ fsfreeze -f "$VAR_FROM"
 sync_var_mountpoints "$VAR_FROM" /mnt || \
     err "Failed to sync var partitions"
 if [ $ERR == 0 ]; then
+    keep_previous_etc_copy "$VAR_FROM" /mnt || \
+        warn "Failed to copy the /etc changes to /etc/previous"
+
     backup_etc_changes "$VAR_FROM" /mnt || \
         warn "Failed to create an /etc backup"
 fi
