Use a service to sync any remaining changes during shutdown.
During shutdown if /run/steamos-post-update-shutdown-booted-slot
exists run steamos-sync-preserved catchup to sync any remaining
changes.
Also check for mountpoints in steamos-sync-preserved and bail if not
mounted previously

diff --git a/atomic-update/rauc/post-install.sh.in b/atomic-update/rauc/post-install.sh.in
--- a/atomic-update/rauc/post-install.sh.in
+++ b/atomic-update/rauc/post-install.sh.in
@@ -31,6 +31,7 @@ ETC_BACKUP_DIR=@etc_backup_dir@
 ATOMIC_UPDATE_CONF_D=@atomic_update_conf_d@
 
 ATOMIC_UPDATE_KEEP_CONF="atomic-update-keep.conf"
+STEAMOS_POST_UPDATE_SHUTDOWN_TRIGGER="/run/steamos-post-update-shutdown-booted-slot"
 
 OWD="$(dirname "$(readlink -f "$0")")"
 
@@ -56,8 +57,8 @@ trap cleanup EXIT
 
 log () { echo >&2 "$@"; }
 warn() { echo >&2 "Warning:" "$@"; }
-err () { echo >&2 "Error:" "$@"; ERR=1; }
-fail() { echo >&2 "Error:" "$@"; exit 1; }
+err () { echo >&2 "Error:" "$@"; rm -f $STEAMOS_POST_UPDATE_SHUTDOWN_TRIGGER; ERR=1; }
+fail() { echo >&2 "Error:" "$@"; rm -f $STEAMOS_POST_UPDATE_SHUTDOWN_TRIGGER; exit 1; }
 
 
 #
@@ -156,6 +157,11 @@ PRESERVED_SLOT=
 UPDATED_SLOT=
 
 log "Booted into slot $BOOTED_SLOT"
+# Record the current booted slot in a temporary file that 
+# triggers the sync during shutdown (steamos-post-update-shutdown.service)
+if ! echo "$BOOTED_SLOT" > $STEAMOS_POST_UPDATE_SHUTDOWN_TRIGGER; then
+    warn "Failed to record booted slot"
+fi
 
 case $BOOTED_SLOT in
     A)
@@ -315,4 +321,7 @@ if [ $ERR == 0 ]; then
   fi
 fi
 
+if [[ $ERR != 0 ]]; then
+    rm -f $STEAMOS_POST_UPDATE_SHUTDOWN_TRIGGER
+fi
 exit $ERR
