Check ESP partition for errors
There is only a single ESP partition (rather than one per slot), but
as for the EFI partition, we'd like to check it for errors on
install. As for the EFI partitions, we expect it to be VFAT, can
tolerate it being exFAT, and anything else is unexpected and
unacceptable for the stability.

Signed-off-by: Ed Smith <ed.smith@collabora.com>

diff --git a/atomic-update/rauc/pre-install.sh.in b/atomic-update/rauc/pre-install.sh.in
--- a/atomic-update/rauc/pre-install.sh.in
+++ b/atomic-update/rauc/pre-install.sh.in
@@ -150,6 +150,16 @@ if check_fat $EFI_DEVICE; then
     fi
 fi
 
+ESP_DEVICE=$(realpath $SYMLINKS_DIR/shared/esp)
+
+if check_fat $ESP_DEVICE; then
+    if ! fsck.vfat -n $ESP_DEVICE; then
+        # Errors found for $ESP_DEVICE
+        warn "Found errors for ${ESP_DEVICE}, attempting repair."
+        fsck.vfat -a $ESP_DEVICE
+    fi
+fi
+
 #
 # Disable all systemd timers
 #
